name: project_uas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  shared_preferences: 
  firebase_core: ^3.10.0
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  get:
  get_storage:
  http:
  intl:
  logger:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  image: assets/images/logo_splash.png
  image_dark: assets/images/logo_splash.png

  android_12:
    image: assets/images/logo_splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo_splash.png
    icon_background_color_dark: "#121212"

  web: false
  
flutter:
  uses-material-design: true
  assets :
  - assets/images/

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/times_new_roman.ttf
        - asset: assets/fonts/times_new_roman_bold.ttf
          weight: 700
        - asset: assets/fonts/times_new_roman_italic.ttf
          style: italic
        - asset: assets/fonts/times_new_roman_bold_italic.ttf
          weight: 700
          style: italic


